spring.application.name=alert-service
# Redis Connection Configuration
# For Spring Boot 3.x (Use spring.redis.host for Spring Boot 2.x)
spring.data.redis.host=fvn-redis
spring.data.redis.port=6379

server.port = 8092
# Optional: Add password if your Redis instance requires one
# spring.data.redis.password=your_redis_password

# Optional: Set a timeout for the connection
spring.data.redis.timeout=60000